name: context-workflow
on:
  workflow_dispatch:
    inputs:

jobs:
  conext-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "github tree: ${{ toJSON(github) }}"
      - name : step2
        run: |
          echo "repository repository: ${{ github.repository }}"
          echo "repository event_name: ${{ github.event_name }}"