name: workflow-timeout
on: push

jobs:
 timeout-job:
   runs-on: ubuntu-latest
   timeout-minutes: 1
   steps:
   - name: step1
     run: |
       count=0
          while true; do
          echo "count: $count"
          count=$((count + 1))
          sleep 1
          done
   - name: step2
     run: echo "step2"

