name: context-workflow
on:
  workflow_dispatch:
    inputs:

jobs:
  conext-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "github tree: ${{ toJSON(github) }}"
          echo "name: ${{ github.event.inputs.name }}"
          echo "environment: ${{ github.event.inputs.environment }}"