name: create-repo-workflow
on: push

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "key": "value",
              "foo": "bar"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEFT_SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK