name: filter-workflow
on:
  push:
    branches:
      - master
      - develop

jobs:
  branch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "${{ github.event_name }}"
          echo "branch: ${{ github.ref }}"