name: filter-workflow
on:
  push:
    branches:
      - main
      - develop

jobs:
  branch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "event_name: ${{ github.event_name }}"
          echo "branch: ${{ github.ref }}"