name: multi_dispatch-workflow
on:
  workflow_dispatch:
    inputs:
      name:
          description: 'Name of the person to greet'
          required: true
          default: 'Mona the Octocat'
          type: string
      environment:
          description: 'Environment to deploy'
          required: true
          default: 'dev'
          type: choice
          options:
            - preprod
            - prod

jobs:
  workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "name: ${{ github.event.inputs.name }}"
          echo "environment: ${{ github.event.inputs.environment }}"