name: path-filter-workflow
on:
  push:
    paths:
      - 'README.md'
      - 'src/**'

jobs:
    path-job:
        runs-on: ubuntu-latest
        steps:
        - name: step1
          run: |
            echo "updated files: ${{ github.event_name }}"
