name: secret-workflow
on:
  push:
    branches:
      - feature/ASD-1126
      - develop

jobs:
  secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "step1 ${{ secrets.level }}"